name: Run Slime Update script

on:
  schedule:
    - cron: '*/30 * * * *' # runs every 30 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      SECRET_CODE: ${{ vars.SECRET_CODE }}
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.6.0'

      - name: Install dependencies
        run: npm install bent jsdom octokit

      - name: Update slimeimwiki2.0
        run: node slimeupdate.js

      - name: Update slimeimwiki1.0
        run: node wikiupdate1-0.js
